config/routes.rb
Gallery::Application.routes.draw do
  resources :static_pages
  resources :works, only: [:index, :show]
  
  root to: 'static_pages#home'

  match '/style',   to: 'static_pages#style'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/work.rb
class Work < ActiveRecord::Base
  attr_accessible :artist, :created_location, :current_location, :date, :medium, :file_name, :price, :title, :description

  validates :artist,			presence: true
  validates :title,  			presence: true
  validates :date, 	 	  	presence: true
  validates :price, 			presence: true
  validates :medium,			presence: true
  validates :file_name, 	presence: true
  

	def next
		Work.first(conditions: ['id > ?', self.id], order: 'id ASC')
	end

	def previous
		Work.last(conditions: ['id < ?', self.id], order: 'id ASC')
	end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def style
  end

  def about
  end

  def contact
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @style = params[:style]
    if @style == 'grid'
  	  @works = Work.paginate(page: params[:page], per_page: 12, order: 'id ASC')
    else
      @works = Work.all
    end
  end

  def show
  	@work = Work.find(params[:id])
    #@first_work = Work.first
    #@last_work  = Work.last
  end

  def new
  	@work = Work.new
  end

  def create
  	@work = Work.new(params[:work])
  	if @work.save
  		redirect_to @work
  	else
  		render 'new'
  	end
  end

  def edit 
    @work = Work.find(params[:id])
  end

  def update
    @work = Work.find(params[:id])
    if @work.update_attributes(params[:work])
      redirect_to @work
    else
      render 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/_button_toolbar.html.erb
<div class="btn-toolbar"; align="right">
  <div class="btn-group">
  	<a class="btn" href= <%= works_path(style: 'grid') %> ><i class="icon-th"></i></a>
    <a class="btn" href= <%= works_path(style: 'list') %> ><i class="icon-th-list"></i></a>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<small>
			<a href="http://twitter.github.io/bootstrap/">bootstrap</a>
		</small>
		<nav>
			<ul>
				<small>
					<li><%= link_to "about",   about_path %></li>
					<li><%= link_to "contact", contact_path %></li>
					<li><a href="http://rubyonrails.org//">ruby on rails</a></li>
				</small>
			</ul>
		</nav>
	</div>
</footer>
			

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
			<%= link_to "The Gallery", root_path, id: "logo"%>
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to "Home", 	 root_path %></li>
						<li><%= link_to "Style", 	 style_path %></li>
						<li><%= link_to "Works",   works_path(style: 'grid') %></li>
					</ul>
				</nav>
			</div>
		</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gallery</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>
<div class="center">
<p>Welcome to the Impressionism web Gallery by Isaac Getto</p>
</br>
<p>
	Use this app to learn about the great art style and specific works 
</p>
</div>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<div class="row">
	<div class="span3">
		<%= image_tag 'profile.jpg', class: 'img-circle' %>
	</div>
	<div class="span6">
		<p align="center">Hi, I'm Isaac...</p>
	</div>
</div>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<div class="row">
	<div class="span3">
		<%= image_tag 'help.jpg', class: 'img-circle' %>
	</div>
	<div class="span1">
		<p></p>
	</div>
	<div class="span6">
		<p>This is the Impressionism web Gallery</p>
	</br>
		<p>View the <%= link_to "art", works_path %></p>
	</div>
</div>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Welcome to the Gallery</h1>
	<p>
		A selection of great Impressionist Works
	</p>

	<%= link_to "See the Art", 	 works_path(style: 'grid'), class: "btn btn-large btn-primary" %>
	<%= link_to "See the Style", style_path, class: "btn btn-large btn-secondary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/static_pages/style.html.erb
<h1>Impressionism</h1>

</br>

<h2>History</h2>
<div class="well">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The Impressionist style began during the 1800's in France. The art movement first got its name from an exhibition in Paris. At this show the group of artists were mockingly labeled 'Impressionists' from the title of Claude Monet's famous work, 'Impression, Sunrise'. Over time, this French based style would diffuse across continents. This spread of influence outside of France can be seen in the work of American painter Mary Cassatt. 
</div>

</br>

<h2>Techniques and Characteristics</h2>
<div class="well">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Due to the increasing development of photography as well as the strict traditional rules of art at the time, the Impressionists wished to depict what could not by captured by a camera, or with the old academic models. Instead of attempting to capture the most accurate and acute detail, these artists would venture to replicate the truest sensation of a given moment. In this pursuit, the Impressionists stessed the significance of the fleeting, ephemeral moment. Subjects thus, would often concern those transient moments of sunrise and sunset. Because of the artists' disinterest with minute detail and their short-lived subject matter, their brushstrokes became loose and visible in order to capture the occasion while it lasted. The texture which this technique often creates enhances the feeling of the momentary. As well, with this style of brushwork the artists depicted movement in a new way. Instead of painting an scene frozen in time, as artists often did in the past, the Impressionists sought to portray the entire action of the subject matter.
</div>

</br>

<h2>The Impressionists</h2>
<div class="well">
	<%= image_tag("timeline.png", align: "center") %> </br>
	(<%= link_to "Wikipedia",  'http://en.wikipedia.org/wiki/Impressionism' %>)
</div>

app/views/works/_index_grid.erb
<div class="row">
  <div class="span6">
    <%= will_paginate %>
  </div>
  <div class="span6">
    <%= render 'layouts/button_toolbar' %>
  </div>
</div>

<ul class="thumbnails per4">
	<% @works.each do |work| %>
  <li class="span3">
    <div class="thumbnail">
      <div class="caption">
      	<%= link_to image_tag(work.file_name, align: "center", class: 'img-rounded'), work %>
	      <h3><%= link_to work.title, work %></h3>
	      <p>Artist: <%= work.artist %></p>
	      <p>Medium: <%= work.medium %></p>
	      <p>Price:  <%= number_to_currency work.price  %></p>
	    </div>
    </div>
  </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/works/_index_list.html.erb
<%= render 'layouts/button_toolbar' %>

<div class="container">
	<table class="table">
		<thead>
			<tr>
				<td>Title</td>
				<td>Artist</td>
				<td>Price</td>
			</tr>
		</thead>
	<% @works.each do |work| %>
	<tr>
		<td><%= link_to work.title, work %></td>
		<td><%= work.artist %></td>
		<td><%= number_to_currency work.price %></td>
	</tr>
	<% end %>
	</table>
</div>

app/views/works/edit.html.erb
<h1>Update artwork</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for @work do |f| %>

			<%= f.label :title %>
			<%= f.text_field :title %>

			<%= f.label :artist %>
			<%= f.text_field :artist %>

			<%= f.label :price %>
			<%= f.text_field :price %>

			<%= f.label :medium %>
			<%= f.text_field :medium %>

			<%= f.label :date %>
			<%= f.date_select :date, discard_day: true, discard_month: true, start_year: 1800 %>

			<%= f.label :file_name, "File name" %>
			<%= f.text_field :file_name %>

			<%= f.label :current_location %>
			<%= f.text_field :current_location %>

			<%= f.label :created_location %>
			<%= f.text_field :created_location %>

			<%= f.label :description %>
			<%= f.text_area :description, rows: 5 %>

			<%= f.submit "Update", class: "btn btn-large btn-primary" %>

		<% end %>
	</div>
</div>

app/views/works/index.html.erb
<h1>Art Works</h1>

<% if @style == 'grid' %>
	<%= render 'index_grid' %>
<% else %>
	<%= render 'index_list' %>
<% end %>

app/views/works/new.html.erb
<h1>Add an artwork</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for @work do |f| %>

			<%= f.label :title %>
			<%= f.text_field :title %>

			<%= f.label :artist %>
			<%= f.text_field :artist %>

			<%= f.label :price %>
			<%= f.text_field :price %>

			<%= f.label :medium %>
			<%= f.text_field :medium %>

			<%= f.label :date %>
			<%= f.date_select :date, discard_day: true, discard_month: true, start_year: 1800 %>

			<%= f.label :file_name, "File name" %>
			<%= f.text_field :file_name %>

			<%= f.label :current_location %>
			<%= f.text_field :current_location %>

			<%= f.label :created_location %>
			<%= f.text_field :created_location %>

			<%= f.label :description %>
			<%= f.text_area :description, rows: 5 %>

			<%= f.submit "Add artwork", class: "btn btn-large btn-primary" %>

		<% end %>
	</div>
</div>

app/views/works/show.html.erb
<h1><%=@work.title%></h1>

<div class="row">
	<div class="span4">
		<p>Artist: 					 					 <%=@work.artist%></p>
		<p>Price: 	 <%=number_to_currency @work.price%></p>
		<p>Medium: 										 <%=@work.medium%></p>
		<p>Date: 												 <%=@work.date.year%></p>

		<!-- <p>Description: <%= @work.description %></p> -->


		<% unless @work.current_location.blank? %>
			<p>Current Location: <%=@work.current_location%></p>
		<% end %>

		<% unless @work.created_location.blank? %>
			<p>Created Location: <%=@work.created_location%></p>
		<% end %>
	</div>
	<div class="span8">
		<%= image_tag @work.file_name, align: 'right', class: 'img-rounded' %>
	</div>
</div>

<div class="row">
	<ul class="pager">
		<% if @work.previous.nil? %>
	  	<li class="previous disabled" >
	    <a href= # >&larr; Previous</a>
    <% else %> 
    	<li class="previous" >
	    <a href= <%= work_path(@work.previous) %> >&larr; Previous</a>
    <% end %>
	  </li>

		<li><a href= <%= works_path(style: 'grid') %>>All Works</a></li>

		<% if @work.next.nil? %>
	  <li class="next disabled" >
	    <a href= # >Next &rarr;</a>
	  <% else %>
	  <li class="next" >
	    <a href= <%= work_path(@work.next) %> >Next &rarr;</a>
	  <% end %>
	  </li>
	</ul>
</div>